### ISSUE TITLE
Tokenomics [milestone]

### ISSUE THREAD

**Issue by peersky** [bugout-dev/dao#23]
- [ ] How should Decentralized crawling project should use MNSTR token to provide fair and competitive market for blockchain crawling?
- [ ] How should our web3 code (`Terminus`) use MNSTR token to provide competitive service while earning for DAO? 
- [ ] How should Moonstream application charge for services it provides?
- [ ] What should be token distribution model, supply etc
- [ ] How should DAO use tokens to provide grants and speed up development
